name = "SemiClassicalMC"
uuid = "c7ea8738-3587-42f3-ae5e-12f8a3b0b641"
authors = ["Lasse Gresista <gresista@thp.uni-koeln.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
